export const LANGUAGE_TO_RECORD_ID = {
  "French": "rec8T090TQT17mCOC",
  "Arabic": "rec7QpnaJ7zLomGK7",
  "Portuguese": "rec3MdK08NshcX8e7",
  "Azeri": "recUijspm1i5nYTCS",
  "Spanish": "recyHZSofVcbzUFe0",
  "English": "recXGdubqU55I5CCb",
  "German": "recf8q035W45WZnkF",
  "Bengali": "recWaE7ype0dqflTW",
  "Armenian": "recCtSqb2ql04B3Om",
  "Dutch": "rec6QPULTr5KxiXY0",
  "Bosnian": "recyre4nyrsYxmVHu",
  "Bulgarian": "rectNpBnjfx47edUT",
  "Chinese (Traditional)": "recJ4x3vGYIguFv1P",
  "Croatian": "rec37HWwY9I4ViiWr",
  "Greek": "recL07Xeal2v0VRRD",
  "Czech": "rec7zxrcNe5zZzkQW",
  "Danish": "recPw6XcZKhOML40C",
  "Estonian": "recwbyjO0j2RDwyqT",
  "Finnish": "recqTz4von4BoqWsC",
  "Hungarian": "recZjR3DX6HCYLHB7",
  "Hindi": "recQDc43ZwORwO73d",
  "Indonesian": "rec58ui79bHiC29T5",
  "Hebrew": "rec3ckSVrbKNF01vn",
  "Italian": "recN15us8R2jrPhNP",
  "Japanese": "recE2oR1Zh8KKPFFT",
  "Russian": "recOf5C11yGGWAiV2",
  "Korean": "recE8E1nMttsqRZ6c",
  "Latvian": "recfqcmm47zNsh4LQ",
  "Lithuanian": "recQDSXlLAhO7LsZU",
  "Malay": "recTpUzHACvLcdAOC",
  "Romanian": "recBA36GJ6JmIP5GN",
  "Norwegian (Bokmål)": "recwRe3gafYMOEXKH",
  "Urdu": "recqaMvqfAehBsPjT",
  "Tagalog": "recrheMSliWTFFrPC",
  "Polish": "recZ3gCZcd0Kk8BUN",
  "Serbian": "recV9kEM6zbRnRUjm",
  "Chinese (Simplified)": "recG31wcGSwRgxMsK",
  "Slovak": "recW6lhxCsdwVlrw1",
  "Vietnamese": "recIakkfBG2yj0leE",
  "Slovenian": "rec7eqYj7XYCSYjLX",
  "Swedish": "recXoarAYWdSwT8c8",
  "Thai": "rechrOy6gKEjWBrO8",
  "Turkish": "recIHTQTX74BOndC0",
  "Ukrainian": "recbag3WBrtdkJRpA",
  "Macedonian": "rec9OYL14mK0WKmI2",
};

export const COUNTRY_TO_RECORD_ID = {
  "Algeria": "rec6hPMETYZ2Oxp7V",
  "Angola": "recuZ8hK9j4vLMnc0",
  "Azerbaijan": "recWGPpsb809Zpysj",
  "Argentina": "recO5M7GoqCyb2xtC",
  "Australia": "recvDaZeePapPUc5l",
  "Austria": "rec0QjuQBXFvrIyMw",
  "Bahrain": "recQirRktjGJjj67o",
  "Bangladesh": "recoKPwzawbCT4nK4",
  "Armenia": "recmMErUDJIqQdbQT",
  "Belgium": "rec80j5YKQhXzQU7f",
  "Bolivia": "recP1ayn8TyV8E1Lz",
  "Bosnia and Herzegovina": "recGkUPu3MXy8Djs4",
  "Brazil": "recAy80nsUom9D01G",
  "Bulgaria": "recS7VLCPTJN1Z0Fq",
  "Myanmar (Burma)": "reckWhGjo9i7dNuCD",
  "Cambodia": "rec5zFbfqzzJ6S3Hi",
  "Cameroon": "recN8BcLoaR25Wsw6",
  "Canada": "recBDQ0sQjXYRoChq",
  "Sri Lanka": "recKi0njYfp33LsIk",
  "Chile": "recGHU68djkXTjRgG",
  "Taiwan": "recejgMHck1v9ucs2",
  "Colombia": "recg1agcYuLElvp1M",
  "Costa Rica": "recRksb0CxVtmcMtp",
  "Croatia": "recbyUICIUYFM2Mga",
  "Cyprus": "recX5ut8mxF53KIsH",
  "Czechia": "rec4JbofHtL7QsaUu",
  "Denmark": "recJ5aoxJx5wVk1Po",
  "Ecuador": "reciZ1igEmJlseMKX",
  "El Salvador": "recDkJ9ykiur5Jpbx",
  "Estonia": "recgZTQyV6CntBdVw",
  "Finland": "recldtL0SlBCrSLke",
  "France": "rechLwGq8tUviap2W",
  "Germany": "reckLZz5eFwcUw1cr",
  "Ghana": "recgTdqJxNbWVAe7b",
  "Greece": "rechdZpOMSL6EHcxy",
  "Guatemala": "recnORi1Rb81uVl23",
  "Hong Kong": "rec7DIhGMP5Hazw14",
  "Hungary": "recOCcBjhoKySrqd5",
  "India": "rec32y5aHDxw5Ghnn",
  "Indonesia": "recWMGukCfyZ1d6XY",
  "Ireland": "recgln4ZC24VUoX8R",
  "Israel": "recLcGrN58Pkf2frq",
  "Italy": "rec3G9JBy0jx7QXlY",
  "Cote d'Ivoire": "recqx6ijMaecd5zuN",
  "Japan": "rec2knLHbiAvYFL8u",
  "Kazakhstan": "recm6mWCcjHotB7JO",
  "Jordan": "recs7Z75cLjueevfz",
  "Kenya": "rec9BEdrTbELQNNPC",
  "South Korea": "recDPrMb58fAOR6uX",
  "Latvia": "recwYLcwILwE3VbKn",
  "Lithuania": "rec0BtGE8Umdlk4Fr",
  "Malaysia": "recYHlGY25dn4rFcM",
  "Malta": "recM83tZ0Rec0FSdF",
  "Mexico": "recBanBBjS7ux0Ms3",
  "Moldova": "recTFpaxdtDBv5ft8",
  "Morocco": "recc1gWbCSbD8ueDb",
  "Netherlands": "rec7qMT4NqTKCknK0",
  "New Zealand": "rec5OsUlswIVrbKpC",
  "Nicaragua": "recOYlix1CKvXNIpQ",
  "Nigeria": "recUiSCznFC0dO6wd",
  "Norway": "rect3uO5QpM4TgSb9",
  "Pakistan": "rec5UHdJkqDwapY3N",
  "Panama": "recRGOAeHoixmD8sD",
  "Paraguay": "recPbOS9qJxJGLxvX",
  "Peru": "recjJOgfElr2kBJ4j",
  "Philippines": "recA0pQCue4UuA4qV",
  "Poland": "rec30c33LIx8l83KE",
  "Portugal": "recuhNx3KGzIzSXLB",
  "Romania": "recgVfjInAyxdIORH",
  "Saudi Arabia": "recysDdlZHlj9G4ix",
  "Senegal": "rece2ZhMbVOTx5NqX",
  "Serbia": "recBmHvjwc2GwBJuV",
  "Singapore": "recWQDT8OV2RnnUcW",
  "Slovakia": "recO2I0VbZOkKgmnM",
  "Vietnam": "recDMONfvRLpvLcJn",
  "Slovenia": "recRnceTExuxAo0UH",
  "South Africa": "recLKyNH7SJweWzDc",
  "Spain": "recS3kjxUVryG06ih",
  "Sweden": "recaMYLpuaGr8uHz8",
  "Switzerland": "recWCl54BpqK73p5n",
  "Thailand": "recYK2dQtq9T0CiWn",
  "United Arab Emirates": "recLvmzr225E4m9QG",
  "Tunisia": "reci2048AnYflXmnF",
  "Turkiye": "reccAAW0IHtsLWaYX",
  "Ukraine": "reckndIye9F6uuKGa",
  "North Macedonia": "recnXdt0dkr1Js2JH",
  "Egypt": "rec6vc9tRAjGpdTbH",
  "United Kingdom": "recrcGtXuaiyuzweA",
  "United States": "recqkawXrCpguAafk",
  "Burkina Faso": "rec1YAfaUcTfmMNzv",
  "Uruguay": "recbdW3vX9K7F6qtb",
  "Venezuela": "recoqFbp2nHAARDtJ",
};
