export const LANGUAGE_TO_RECORD_ID = {
  "French": "rec8T090TQT17mCOC",
  "Arabic": "rec7QpnaJ7zLomGK7",
  "Portuguese": "rec3MdK08NshcX8e7",
  "Azeri": "recUijspm1i5nYTCS",
  "Spanish": "recyHZSofVcbzUFe0",
  "English": "recXGdubqU55I5CCb",
  "German": "recf8q035W45WZnkF",
  "Bengali": "recWaE7ype0dqflTW",
  "Armenian": "recCtSqb2ql04B3Om",
  "Dutch": "rec6QPULTr5KxiXY0",
  "Bosnian": "recyre4nyrsYxmVHu",
  "Bulgarian": "rectNpBnjfx47edUT",
  "Chinese (Traditional)": "recJ4x3vGYIguFv1P",
  "Croatian": "rec37HWwY9I4ViiWr",
  "Greek": "recL07Xeal2v0VRRD",
  "Czech": "rec7zxrcNe5zZzkQW",
  "Danish": "recPw6XcZKhOML40C",
  "Estonian": "recwbyjO0j2RDwyqT",
  "Finnish": "recqTz4von4BoqWsC",
  "Hungarian": "recZjR3DX6HCYLHB7",
  "Hindi": "recQDc43ZwORwO73d",
  "Indonesian": "rec58ui79bHiC29T5",
  "Hebrew": "rec3ckSVrbKNF01vn",
  "Italian": "recN15us8R2jrPhNP",
  "Japanese": "recE2oR1Zh8KKPFFT",
  "Russian": "recOf5C11yGGWAiV2",
  "Korean": "recE8E1nMttsqRZ6c",
  "Latvian": "recfqcmm47zNsh4LQ",
  "Lithuanian": "recQDSXlLAhO7LsZU",
  "Malay": "recTpUzHACvLcdAOC",
  "Romanian": "recBA36GJ6JmIP5GN",
  "Norwegian (Bokmål)": "recwRe3gafYMOEXKH",
  "Urdu": "recqaMvqfAehBsPjT",
  "Tagalog": "recrheMSliWTFFrPC",
  "Polish": "recZ3gCZcd0Kk8BUN",
  "Serbian": "recV9kEM6zbRnRUjm",
  "Chinese (Simplified)": "recG31wcGSwRgxMsK",
  "Slovak": "recW6lhxCsdwVlrw1",
  "Vietnamese": "recIakkfBG2yj0leE",
  "Slovenian": "rec7eqYj7XYCSYjLX",
  "Swedish": "recXoarAYWdSwT8c8",
  "Thai": "rechrOy6gKEjWBrO8",
  "Turkish": "recIHTQTX74BOndC0",
  "Ukrainian": "recbag3WBrtdkJRpA",
  "Macedonian": "rec9OYL14mK0WKmI2",
};
