import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    const { email, keyword, questions } = await request.json()

    if (!email || !keyword || !questions || !Array.isArray(questions)) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      )
    }

    if (!process.env.RESEND_API_KEY) {
      console.error('RESEND_API_KEY not configured')
      return NextResponse.json(
        { success: false, error: 'Email service not configured' },
        { status: 500 }
      )
    }

    // Initialize Resend with API key at runtime
    const resend = new Resend(process.env.RESEND_API_KEY)

    // Create HTML email content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Your Questions Discovery Report</title>
        </head>
        <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc;">
          <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
            <!-- Header -->
            <div style="text-align: center; margin-bottom: 40px;">
              <h1 style="color: #1e293b; font-size: 28px; font-weight: 700; margin: 0 0 10px 0;">
                Your Questions Discovery Report
              </h1>
              <p style="color: #64748b; font-size: 16px; margin: 0;">
                Top questions people are asking about "${keyword}"
              </p>
            </div>

            <!-- Questions List -->
            <div style="background-color: #ffffff; border-radius: 12px; padding: 30px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
              <h2 style="color: #1e293b; font-size: 20px; font-weight: 600; margin: 0 0 20px 0;">
                Questions to Answer
              </h2>
              
              ${questions
                .map(
                  (q: string, i: number) => `
                <div style="margin-bottom: 15px; padding: 15px; background-color: #f8fafc; border-left: 4px solid #3b82f6; border-radius: 6px;">
                  <div style="display: flex; align-items: start; gap: 12px;">
                    <span style="background-color: #3b82f6; color: #ffffff; border-radius: 50%; width: 24px; height: 24px; display: inline-flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 600; flex-shrink: 0;">
                      ${i + 1}
                    </span>
                    <p style="margin: 0; color: #334155; font-size: 15px; line-height: 1.6;">
                      ${q}
                    </p>
                  </div>
                </div>
              `
                )
                .join('')}
            </div>

            <!-- CTA Section -->
            <div style="margin-top: 40px; text-align: center; padding: 30px; background-color: #ffffff; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
              <h3 style="color: #1e293b; font-size: 18px; font-weight: 600; margin: 0 0 10px 0;">
                Want help answering these questions?
              </h3>
              <p style="color: #64748b; font-size: 14px; margin: 0 0 20px 0;">
                Book a free discovery call to learn how we can boost your Ai visibility
              </p>
              <a href="https://sewo.io/book-call" style="display: inline-block; background-color: #3b82f6; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 8px; font-weight: 600; font-size: 14px;">
                Book a Discovery Call
              </a>
            </div>

            <!-- Footer -->
            <div style="margin-top: 30px; text-align: center; color: #94a3b8; font-size: 12px;">
              <p style="margin: 0 0 5px 0;">
                This report was generated by <a href="https://sewo.io" style="color: #3b82f6; text-decoration: none;">Your Friends at SEWO</a>
              </p>
              <p style="margin: 0;">
                Helping brands get discovered by Ai
              </p>
            </div>
          </div>
        </body>
      </html>
    `

    // Send email via Resend
    const { data, error } = await resend.emails.send({
      from: 'Stuart A <stuartr@sewo.io>', // Update this with your verified domain
      to: [email],
      subject: `Your Questions Discovery Report: ${keyword}`,
      html: htmlContent,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json(
        { success: false, error: 'Failed to send email' },
        { status: 500 }
      )
    }

    console.log('Email sent successfully:', data)
    return NextResponse.json({ success: true, messageId: data?.id })
  } catch (error) {
    console.error('Send questions email error:', error)
    return NextResponse.json(
      { success: false, error: 'Unexpected error' },
      { status: 500 }
    )
  }
}

